import classnames from 'classnames'
import useTranslation from 'next-translate/useTranslation'
import React from 'react'
import { Emojis } from '~/interfaces'

const emojiCSS: Emojis = {
  /* anywhere out there */
  coffee: 'em-coffee',
  'flag-ar': 'em-flag-ar',
  earth_americas: 'em-earth_americas',
  us: 'em-us',
  /* in the last numbers section */
  sweat_drops: 'em-sweat_drops',
  boy: 'em-boy',
  pray: 'em-pray',
  bed: 'em-bed',
  cat: 'em-cat',
  dog: 'em-dog',
  gun: 'em-gun',
  fire: 'em-fire',
  ocean: 'em-ocean',
  glass_of_milk: 'em-glass_of_milk',
  chopsticks: 'em-chopsticks',
  'male-guard': 'em-male-guard',
  cold_face: 'em-cold_face',
  beers: 'em-beers',
  girl: 'em-girl',
  ring: 'em-ring',
  'man-facepalming': 'em-man-facepalming',
  syringe: 'em-syringe',
  fish: 'em-fish',
  partying_face: 'em-partying_face',
  woman: 'em-woman',
  smirk: 'em-smirk',
  butterfly: 'em-butterfly',
  horse: 'em-horse',
  chicken: 'em-chicken',
  church: 'em-church',
  'man-getting-haircut': 'em-man-getting-haircut',
  mountain: 'em-mountain',
  rain_cloud: 'em-rain_cloud',
  bulb: 'em-bulb',
  moneybag: 'em-moneybag',
  exploding_head: 'em-exploding_head',
  bird: 'em-bird',
  bread: 'em-bread',
  tooth: 'em-tooth',
  oil_drum: 'em-oil_drum',
  thunder_cloud_and_rain: 'em-thunder_cloud_and_rain',
  hocho: 'em-hocho',
  athletic_shoe: 'em-athletic_shoe',
  frame_with_picture: 'em-frame_with_picture',
  x: 'em-x',
  wine_glass: 'em-wine_glass',
  tomato: 'em-tomato',
  zombie: 'em-zombie',
  male_zombie: 'em-male_zombie',
  cut_of_meat: 'em-cut_of_meat',
  baguette_bread: 'em-baguette_bread',
  toolbox: 'em-toolbox',
  pregnant_woman: 'em-pregnant_woman',
  ship: 'em-ship',
  cow: 'em-cow',
  es: 'em-es',
  hole: 'em-hole',
  dromedary_camel: 'em-dromedary_camel',
  ambulance: 'em-ambulance',
  cactus: 'em-cactus',
  angel: 'em-angel',
  couple_with_heart: 'em-couple_with_heart',
  sob: 'em-sob',
  bow_and_arrow: 'em-bow_and_arrow',
  bug: 'em-bug',
  snake: 'em-snake',
  'man-boy': 'em-man-boy',
  pill: 'em-pill',
  female_zombie: 'em-female_zombie',
  hankey: 'em-hankey',
  gift: 'em-gift',
  hospital: 'em-hospital',
  '8ball': 'em-8ball',
  clown_face: 'em-clown_face',
  llama: 'em-llama',
  leg: 'em-leg',
  lips: 'em-lips',
  chains: 'em-chains',
  soccer: 'em-soccer',
  bouquet: 'em-bouquet',
  boxing_glove: 'em-boxing_glove',
  cloud: 'em-cloud',
  flashlight: 'em-flashlight',
  wind_blowing_face: 'em-wind_blowing_face',
  guitar: 'em-guitar',
  potato: 'em-potato',
  rat: 'em-rat',
  scream: 'em-scream',
}

const emojiLabel: Emojis = {
  /* anywhere out there */
  coffee: 'common:coffee',
  'flag-ar': 'jugar:flag-ar',
  earth_americas: 'jugar:world',
  us: 'jugar:flag-us',
  /* in the last numbers section */
  sweat_drops: 'jugar:dreams.1',
  boy: 'jugar:dreams.2',
  pray: 'jugar:dreams.3',
  bed: 'jugar:dreams.4',
  cat: 'jugar:dreams.5',
  dog: 'jugar:dreams.6',
  gun: 'jugar:dreams.7',
  fire: 'jugar:dreams.8',
  ocean: 'jugar:dreams.9',
  glass_of_milk: 'jugar:dreams.10',
  chopsticks: 'jugar:dreams.11',
  'male-guard': 'jugar:dreams.12',
  cold_face: 'jugar:dreams.13',
  beers: 'jugar:dreams.14',
  girl: 'jugar:dreams.15',
  ring: 'jugar:dreams.16',
  'man-facepalming': 'jugar:dreams.17',
  syringe: 'jugar:dreams.18',
  fish: 'jugar:dreams.19',
  partying_face: 'jugar:dreams.20',
  woman: 'jugar:dreams.21',
  smirk: 'jugar:dreams.22',
  butterfly: 'jugar:dreams.23',
  horse: 'jugar:dreams.24',
  chicken: 'jugar:dreams.25',
  church: 'jugar:dreams.26',
  'man-getting-haircut': 'jugar:dreams.27',
  mountain: 'jugar:dreams.28',
  rain_cloud: 'jugar:dreams.30',
  bulb: 'jugar:dreams.31',
  moneybag: 'jugar:dreams.32',
  exploding_head: 'jugar:dreams.34',
  bird: 'jugar:dreams.35',
  bread: 'jugar:dreams.36',
  tooth: 'jugar:dreams.37',
  oil_drum: 'jugar:dreams.38',
  thunder_cloud_and_rain: 'jugar:dreams.39',
  hocho: 'jugar:dreams.41',
  athletic_shoe: 'jugar:dreams.42',
  frame_with_picture: 'jugar:dreams.43',
  x: 'jugar:dreams.44',
  wine_glass: 'jugar:dreams.45',
  tomato: 'jugar:dreams.46',
  zombie: 'jugar:dreams.47',
  male_zombie: 'jugar:dreams.48',
  cut_of_meat: 'jugar:dreams.49',
  baguette_bread: 'jugar:dreams.50',
  toolbox: 'jugar:dreams.51',
  pregnant_woman: 'jugar:dreams.52',
  ship: 'jugar:dreams.53',
  cow: 'jugar:dreams.54',
  es: 'jugar:dreams.55',
  hole: 'jugar:dreams.56',
  dromedary_camel: 'jugar:dreams.57',
  ambulance: 'jugar:dreams.58',
  cactus: 'jugar:dreams.59',
  angel: 'jugar:dreams.60',
  couple_with_heart: 'jugar:dreams.63',
  sob: 'jugar:dreams.64',
  bow_and_arrow: 'jugar:dreams.65',
  bug: 'jugar:dreams.66',
  snake: 'jugar:dreams.67',
  'man-boy': 'jugar:dreams.68',
  pill: 'jugar:dreams.69',
  female_zombie: 'jugar:dreams.70',
  hankey: 'jugar:dreams.71',
  gift: 'jugar:dreams.72',
  hospital: 'jugar:dreams.73',
  '8ball': 'jugar:dreams.74',
  clown_face: 'jugar:dreams.75',
  llama: 'jugar:dreams.76',
  leg: 'jugar:dreams.77',
  lips: 'jugar:dreams.78',
  chains: 'jugar:dreams.79',
  soccer: 'jugar:dreams.80',
  bouquet: 'jugar:dreams.81',
  boxing_glove: 'jugar:dreams.82',
  cloud: 'jugar:dreams.83',
  flashlight: 'jugar:dreams.85',
  wind_blowing_face: 'jugar:dreams.86',
  guitar: 'jugar:dreams.87',
  potato: 'jugar:dreams.88',
  rat: 'jugar:dreams.89',
  scream: 'jugar:dreams.90',
}

interface Props {
  name: keyof Emojis
}

export default function Emoji({ name }: Props) {
  const { t } = useTranslation()

  return (
    <i
      className={classnames(['em', emojiCSS[name]])}
      tabIndex={-1}
      aria-label={t(emojiLabel[name])}
    ></i>
  )
}
