export interface Emojis {
  /* anywhere out there */
  coffee: string
  'flag-ar': string
  earth_americas: string
  us: string
  /* room code */
  deciduous_tree: string
  snail: string
  game_die: string
  tornado: string
  airplane: string
  rainbow: string
  basketball: string
  volcano: string
  banana: string
  /* in the "Last numbers" section */
  sweat_drops: string
  boy: string
  pray: string
  bed: string
  cat: string
  dog: string
  gun: string
  fire: string
  ocean: string
  glass_of_milk: string
  chopsticks: string
  'male-guard': string
  cold_face: string
  beers: string
  girl: string
  ring: string
  'man-facepalming': string
  syringe: string
  fish: string
  partying_face: string
  woman: string
  smirk: string
  butterfly: string
  horse: string
  chicken: string
  church: string
  'man-getting-haircut': string
  mountain: string
  rain_cloud: string
  bulb: string
  moneybag: string
  exploding_head: string
  bird: string
  bread: string
  tooth: string
  oil_drum: string
  thunder_cloud_and_rain: string
  hocho: string
  athletic_shoe: string
  frame_with_picture: string
  x: string
  wine_glass: string
  tomato: string
  zombie: string
  male_zombie: string
  cut_of_meat: string
  baguette_bread: string
  toolbox: string
  pregnant_woman: string
  ship: string
  cow: string
  es: string
  hole: string
  dromedary_camel: string
  ambulance: string
  cactus: string
  angel: string
  couple_with_heart: string
  sob: string
  bow_and_arrow: string
  bug: string
  snake: string
  'man-boy': string
  pill: string
  female_zombie: string
  hankey: string
  gift: string
  hospital: string
  '8ball': string
  clown_face: string
  llama: string
  leg: string
  lips: string
  chains: string
  soccer: string
  bouquet: string
  boxing_glove: string
  cloud: string
  flashlight: string
  wind_blowing_face: string
  guitar: string
  potato: string
  rat: string
  scream: string
}
